// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations.FavoriteMusic
{
    [DbContext(typeof(FavoriteMusicContext))]
    partial class FavoriteMusicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.FavoriteMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavSong1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavSong2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavSong3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavSong4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteSongs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavSong1 = "Friends - Led Zeppelin",
                            FavSong2 = "Celebration Day - Led Zeppelin",
                            FavSong3 = "Jungle - ELO",
                            FavSong4 = "Tightrope - ELO"
                        },
                        new
                        {
                            Id = 2,
                            FavSong1 = "Wild West Hero - ELO",
                            FavSong2 = "Running Up That Hill - Kate Bush",
                            FavSong3 = "Master of Puppets - Metallica",
                            FavSong4 = "Every Breath You Take - The Police"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
