// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations.FavoriteFood
{
    [DbContext(typeof(FavoriteFoodContext))]
    [Migration("20220726210036_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.FavoriteFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavBreak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavDes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavDin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavLunch")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteFood");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavBreak = "French Toast",
                            FavDes = "Cheesecake",
                            FavDin = "Pad Thai",
                            FavLunch = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            FavBreak = "Pancakes",
                            FavDes = "Brownies",
                            FavDin = "Spaghetti",
                            FavLunch = "Subs"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.TeamName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
